config/routes.rb
Rails.application.routes.draw do
 

  resources :favourites

  root "home#index"

  patch "tasks/:id/" => "tasks#toggle_status", as: :toggle_task_status

  get "projects/favourites/" => "projects#favourite"

  resources :projects do
    resources :favourites, only: [:create, :destroy]
    resources :tasks
    resources :discussions do
      resources :comments
    end
  end

  get "/about" => "home#about"

  devise_for :users, :controllers => { :registrations => "registrations" }

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  validates :title, presence: true

  belongs_to :project
  belongs_to :user
  has_many :comments, dependent: :destroy
end

# Project: title(required & unique), description and due_date
# Task: title (required & unique within a project) and due_date
# Discussion: title(required), description
# Comment: body(required)

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def index
    @project = Project.find params[:project_id]
    # @discussions = @project.discussions
    @discussion = Discussion.new
    @discussion.user = current_user
  end

  def show
    @project = Project.find params[:project_id]
    @discussion = @project.discussions.find params[:id]
    @comment = Comment.new
    @comment.user = current_user
  end

  def new
    @discussion = Discussion.new
  end

  def edit
    @project = Project.find params[:project_id]
    @discussion = Discussion.find params[:id]
  end

  def create
    @project = Project.find params[:project_id]
    @discussion = Discussion.new discussion_params
    @discussion.project = @project
    @discussion.user = current_user
    if @discussion.save
      redirect_to project_discussions_path(@project), notice: "Discussion created successfully!"
    else 
      redirect_to project_discussions_path(@project), alert: "Unable to create discussion"
    end 
  end

  def update
    @project = Project.find params[:project_id]
    @discussion = @project.discussions.find params[:id]
    if @discussion.update discussion_params
      redirect_to project_discussions_path(@project), notice: "Discussion edited successfully!"
    else 
      redirect_to project_discussions_path(@project), alert: "Unable to edit discussion"
    end
  end

  def destroy
    @project = Project.find params[:project_id]
    @discussion = Discussion.find params[:id]
    if @discussion.destroy
      redirect_to project_discussions_path(@project), notice: "Discussion deleted!"
    else
      redirect_to project_discussions_path(@project), notice: "Unable to delete discussion"
    end
  end

  private

  def discussion_params
    params.require(:discussion).permit(:title, :description, :user_id)
  end

end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.erb
<div class="container">
  <%= form_for [@project, @discussion] do |f| %>
    <%= f.label :title %>
    <%= f.text_area :title, class:"form-control" %><br>
    <%= f.label :description %>
    <%= f.text_field :description, class:"form-control"%><br>
    <%= f.submit class: "btn btn-info btn-sm" %>
  <% end %>
</div>

app/views/discussions/edit.html.erb
<div class="container">
  <h2>Edit Discussion Discussion</h2>
  <%= render 'form' %>
</div>

app/views/discussions/index.html.erb
<div class="container">
  <h2>Discussions for <%= @project.title %></h2>
</div>

<div class="container">
  <% @project.discussions.each do |discussion| %>
    <h3>Title: <%= link_to discussion.title, project_discussion_path(@project, discussion) %></h3>
    <p>Description:<%= discussion.description %></p>
    <%= link_to "Edit Discussion", edit_project_discussion_path(@project, discussion), class: "btn btn-primary btn-xs" %>
    <%= link_to "Abolish Discussion",
    project_discussion_path(@project, discussion), method: :delete, data: {
      confirm: "Are you sure you wish to abolish this discussion?"}, class: "btn btn-danger btn-xs" %>
  <% end %>
</div>

<br>

<div class="container">
  <h4>Start a New Discussion for: <%= @project.title %></h4>
  <%= form_for [@project, @discussion] do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control" %><br>
    <%= f.label :description %>
    <%= f.text_field :description, class:"form-control"%><br>
    <%= f.submit class: "btn btn-info btn-md" %>
  <% end %>
</div>

 

app/views/discussions/show.html.erb
<div class="container">
  <h1>Discussion: <%= @discussion.title %></h1>
  <h4>Description: <%= @discussion.description %></h4>
  <div class="well">
    <% @discussion.comments.each do |comment| %>
      <%= render partial: 'comments/comment_row', locals: { comment: comment } %>
    <% end %>
  </div>
</div>


<div class="container">
 <%= form_for @comment, url: project_discussion_comments_path(@project, @discussion), remote: true do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body, class:"form-control" %><br>
  <%= f.submit class: "btn btn-info btn-sm" %>
  <% end %>
</div>