config/routes.rb
Rails.application.routes.draw do
 

  resources :favourites

  root "home#index"

  patch "tasks/:id/" => "tasks#toggle_status", as: :toggle_task_status

  get "projects/favourites/" => "projects#favourite"

  resources :projects do
    resources :favourites, only: [:create, :destroy]
    resources :tasks
    resources :discussions do
      resources :comments
    end
  end

  get "/about" => "home#about"

  devise_for :users, :controllers => { :registrations => "registrations" }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true
  belongs_to :discussion
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController 
  respond_to :js, :html

  def index
    @discussion = Discussion.find params[:discussion_id]
  end

  def new
    @comment = Comment.new
  end

  def edit
    @project = Project.find params[:project_id]
    @discussion = Discussion.find params[:discussion_id]
    @comment = Comment.find params[:id]
  end

  def create
    @project = Project.find params[:project_id]
    @discussion = Discussion.find params[:discussion_id]
    @comment = @discussion.comments.create comment_params
    @comment.user = current_user
    # @comment.discussion_id = @discussion.id
    if @comment.save && @discussion.user != current_user
      respond_with ()
      DiscussionMailer.delay.notify_discussion_owner(@comment)
      #redirect_to project_discussion_path(@discussion.project, @discussion), notice: "Comment Created!"
    elsif @comment.save
      respond_with ()
      #redirect_to project_discussion_path(@discussion.project, @discussion), notice: "Comment Created!"
    else
      #redirect_to project_discussion_path(@discussion.project, @discussion), notice: "Comments cannot be blank!"
      respond_with ()
    end
  end

  def update
    @discussion = Discussion.find params[:discussion_id]
    @comment = @discussion.comments.find params[:id]
    if @comment.update comment_params
      redirect_to project_discussion_path(@discussion.project, @discussion), notice: "Comment edited successfully"
    else 
      redirect_to project_discussion_path(@discussion.project, @discussion), alert: "Unable to edit comment"
    end
  end

  def destroy
    @project = Project.find params[:project_id]
    @discussion = Discussion.find params[:discussion_id]
    @comment = Comment.find params[:id]
    if @comment.destroy
      respond_with ()
    else #redirect_to project_discussion_path(@discussion.project, @discussion), notice: "Comment Abolished!"
      respond_with ()
    end
  end

  private 

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_row.html.erb
<div id="<%= dom_id(comment)%>">
  <h3><%= comment.body %></h3>
  <h5><%= comment.created_at %></h5>
  <h5>Posted By: <%= comment.user.first_name %></h5>
  <%= link_to "Edit Comment", edit_project_discussion_comment_path(@project, @discussion, comment), class: "btn btn-primary btn-xs" %>
  <%= link_to "Abolish Comment", project_discussion_comment_path(@project, @discussion, comment), method: :delete, data: {
  confirm: "Are you sure you wish to abolish this comment?"}, class: "btn btn-danger btn-xs", remote: true %>
</div>

app/views/comments/create.js.erb
$('#comment_body').val('')
$('.well').append("<%= j render partial: 'comments/comment_row', locals: {comment: @comment} %>");

app/views/comments/destroy.js.erb
$('#<%= dom_id(@comment) %>').fadeOut();

app/views/comments/edit.html.erb
<div class="container">
 <%= form_for @comment, url: project_discussion_comment_path(@project, @discussion, @comment) do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body, class:"form-control" %><br>
    <%= f.submit class: "btn btn-info btn-sm" %>
  <% end %>
</div>