config/routes.rb
Rails.application.routes.draw do
 

  resources :favourites

  root "home#index"

  patch "tasks/:id/" => "tasks#toggle_status", as: :toggle_task_status

  get "projects/favourites/" => "projects#favourite"

  resources :projects do
    resources :favourites, only: [:create, :destroy]
    resources :tasks
    resources :discussions do
      resources :comments
    end
  end

  get "/about" => "home#about"

  devise_for :users, :controllers => { :registrations => "registrations" }

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :title, presence: true, uniqueness: {scope: :project_id}
  belongs_to :project
  belongs_to :user
end
# Project: title(required & unique), description and due_date
# Task: title (required & unique within a project) and due_date
# Discussion: title(required), description
# Comment: body(required)

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  respond_to :js, :html

  def index
    @task = Task.order(:status)
  end

  def show
    @task = Task.find params[:id]
  end

  def new
    @task = Task.new 
  end

  def edit
    @project = Project.find params[:project_id]
    @task = Task.find params[:id]
  end

  def create
    @project = Project.find params[:project_id]
    @task = @project.tasks.new task_params
    @task.status = false
    @task.user = current_user
    if @task.save
      respond_with ()
      #redirect_to @project, notice: "Task created successfully!"
    else
      respond_with ()
      #redirect_to @project, alert: "Error in creating your task"
    end
  end

  def update
    @project = Project.find params[:project_id]
    @task = @project.tasks.find params[:id]
    if @task.update task_params
      redirect_to project_path(@project), notice: "Task edited successfully!"
    else
      redirect_to project_path(@project), alert: "Unable to edit task"
    end
  end

  def destroy
    @project = Project.find params[:project_id]
    @task = Task.find params[:id]
    if @task.destroy
      respond_with ()
      #redirect_to project_path(@project), notice: "Task Abolished!"
    else
      respond with ()
    end
  end

  def toggle_status
    @task = Task.find params[:id]
    if @task.status == false && @task.user != current_user
      TaskMailer.delay.notify_task_owner(@task)
      @task.status = true
    elsif @task.status == false
      @task.status = true
    elsif @task.status == true
      @task.status = false
    end
    @task.save
    respond_with ()
    #redirect_to project_path(@task.project_id)
  end

  private

  def task_params
    params.require(:task).permit([:title, :due_date])
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_task_project.html.erb
 <div class="container">
  <div class="row">  
    <div class="col-md-6">
      <h2>Incomplete Tasks for: <%= @project.title %></h2>
      <div class="incomplete-task-well">
        <% @tasks.each do |task| %>
          <% if task.status == false %>
            <%= render partial: 'tasks/task_row', locals: { task: task } %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-md-6"> 
      <h2>Complete Tasks for: <%= @project.title %></h2>
      <div class="complete-task-well">
        <% @tasks.each do |task| %>
          <% if task.status == true %>
            <%= render partial: 'tasks/task_row', locals: { task: task } %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">
<h2>Add New Task</h2>
<% if @task.errors.any? %>
  <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @task, url: project_tasks_path(@project), remote: true do |f| %>
  <%= f.label :title %>
  <%= f.text_area :title, class:"form-control" %><br>
  <%= f.label :due_date %>
  <%= f.date_field :due_date %>
  <%= f.submit class: "btn btn-info btn-sm" %>
<% end %>
</div>
<br>
<br>
<hr>

app/views/tasks/_task_row.html.erb
<div id="<%= dom_id(task)%>">
  <h5><%= task.title %></h5>
  <p>Complete By:<%= task.due_date %></p>
  <p>Created By: <%= task.user.first_name %></p>
  <%= link_to "Edit Task", edit_project_task_path(@project, task), class: "btn btn-primary btn-xs" %>
  <%= link_to "Abolish Task",
  project_task_path(@project, task), method: :delete, data: {
    confirm: "Are you sure you wish to abolish this task?"}, class: "btn btn-danger btn-xs", remote: true %>
    <% if task.status == true %>
      <%= link_to "Done", toggle_task_status_path(task), method: :patch, class: "btn btn-success btn-xs", remote: true %>
    <% elsif task.status == false %>
      <%= link_to "Not Done", toggle_task_status_path(task), method: :patch, class: "btn btn-warning btn-xs", remote: true %>
    <% end %>
</div>

app/views/tasks/create.js.erb
$('#task_title').val('')
$('.incomplete-task-well').prepend("<%= j render partial: '/tasks/task_row', locals: {task: @task} %>");

app/views/tasks/destroy.js.erb
$('#<%= dom_id(@task) %>').fadeOut();

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit Task</h1>
  <p>Let's shake things up a bit</p>
</div>

<div class="container">
  <%= form_for [@project, @task] do |f| %>
    <%= f.label :title %>
    <%= f.text_area :title, class:"form-control" %><br>
    <%= f.label :due_date %>
    <%= f.date_field :due_date, class:"form-control"%><br>
    <%= f.submit class: "btn btn-info btn-sm" %>
  <% end %>
</div>

app/views/tasks/toggle_status.js.erb
// if( $('#<%= dom_id(@task) %> a').eq(2).html() === 'Done' ) {
//   $('#<%= dom_id(@task) %> a').eq(2).html('Not Done').addClass('btn btn-warning btn-xs'); 
// }
// else if ( $('#<%= dom_id(@task) %> a').eq(2).html() === 'Not Done' ){
//   $('#<%= dom_id(@task) %> a').eq(2).html('Done').removeClass('btn btn-warning btn-xs').addClass('btn btn-success btn-xs'); 
// }


if( $('#<%= dom_id(@task) %> a').eq(2).html() === 'Done' ) {
  $('#<%= dom_id(@task) %> a').eq(2).html('Not Done').addClass('btn btn-warning btn-xs'); 
}
else {
  $('#<%= dom_id(@task) %> a').eq(2).html('Done').removeClass('btn btn-warning btn-xs').addClass('btn btn-success btn-xs'); 
}