config/routes.rb
Rails.application.routes.draw do
 

  resources :favourites

  root "home#index"

  patch "tasks/:id/" => "tasks#toggle_status", as: :toggle_task_status

  get "projects/favourites/" => "projects#favourite"

  resources :projects do
    resources :favourites, only: [:create, :destroy]
    resources :tasks
    resources :discussions do
      resources :comments
    end
  end

  get "/about" => "home#about"

  devise_for :users, :controllers => { :registrations => "registrations" }

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, uniqueness: true
  has_many :tasks, dependent: :nullify
  has_many :discussions, dependent: :nullify
  
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

  has_many :project_tags, dependent: :destroy
  has_many :tags, through: :project_tags

  has_many :favourites, dependent: :destroy
  has_many :favourited_users, through: :favourites, source: :user
  
  def self.search(query)
    where("title ilike ? OR description ilike ?", "%#{query}%", "%#{query}%") 
  end
end



# Project: title(required & unique), description and due_date
# Task: title (required & unique within a project) and due_date
# Discussion: title(required), description
# Comment: body(required)

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def index
    @projects = Project.order(:title)
    if params[:search]
      @projects = Project.search(params[:search]).order(:title)
    else
      @projects = Project.all.order(:title)
    end
  end

  def show
    @project = Project.find params[:id]
    @projects = Project.order params[:title]
    @task = Task.new
    @discussion = Discussion.new
    @tasks = @project.tasks.order(:created_at)
    @favourite = current_user.favourite_for(@project)
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find params[:id]
  end

  def create
    @project = Project.new project_params
    @project.user = current_user
    if @project.save
      redirect_to projects_path
    else 
      render new_project_path, notice: "Did you remember to include a Title for your project?"
    end
  end

  def update
    @project = Project.find params[:id]
    if @project.update project_params
      redirect_to project_path, notice: "Project updated!"
    else
      render edit_project_path, alert: "Unable to update project"
    end
  end

  def destroy
    @project = Project.find params[:id]
    @project.destroy
    redirect_to projects_path
  end

  def favourite
    @projects = Project.find(current_user.favourites.map(&:project_id))
  end

  private

  def project_params
    params.require(:project).permit([:title, :description, :due_date, {user_ids: []},
                                                                      {tag_ids: []}])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project_form.html.erb
<%= form_for @project do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class:"form-control" %><br>
  <%= f.label :description %>
  <%= f.text_field :description, class:"form-control" %><br>
  <%= f.label :due_date %>
  <%= f.date_field :due_date, class:"form-control" %><br>
  <%= f.label :memberships_id %><br>
  <%= f.collection_check_boxes :user_ids, User.all, :id, :full_name %><br>
  <%= f.label :tags %><br>
  <%= f.collection_check_boxes :tag_ids, Tag.order("title"), :id, :title %>
  <%= f.submit class: "btn btn-info btn-md" %>
<% end %>

app/views/projects/edit.html.erb
<div class="container">
  <h1>Edit an Existing Project</h1>
  <p> lets shake things up a bit </p>
</div>

<hr>

<div class="container">
  <%= render 'project_form' %>
</div>

app/views/projects/favourite.html.erb
<div class="container">
  <h1>My Favourited Projects</h1>
  <p>lets get to work!!</p>
  <hr>
</div>

<div class="container">
<% @projects.each do |project| %> 
  <h3><%= link_to project.title, project_path(project) %></h3>
  <p>Title:<%= project.title %></p>
  <p>Description:<%= project.description %></p>
  <p>Due:<%= project.due_date %></p>
  <hr>
<% end %>
</div>

app/views/projects/index.html.erb
<div class="container">
  <h1>Projects</h1>
  <% if current_user == nil %>
    <p>You must be signed in to view a project!</p>
  <% else %>
    <p>lets get to work!!</p>
  <% end %>
  <hr>
</div>


<div class="container">
<%= form_tag(projects_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Projects", class: "form-control" %><br>
  <%= submit_tag "Search", :title => nil, class: "btn btn-primary btn-lg" %>
<% end %>
</div>

<div class="container">
  <% @projects.each do |f| %>
    <h3><%= link_to f.title, project_path(f) %></h3>
    <p>Title:<%= f.title %></p>
    <p>Description:<%= f.description %></p>
    <p>Due:<%= f.due_date %></p>
    <hr>
  <% end %>
</div>  

app/views/projects/new.html.erb
<div class="container">
  <h1>Start a New Project</h1>
  <p> lets get this party started!!</p>
</div>

  <hr>

<div class="container">
  <%= render 'project_form' %>
</div>

app/views/projects/show.html.erb
<div class="container">
  <h1><%= @project.title %></h1>
  <p> don't stop now.. </p>
</div>

<div class="container">
  <p><strong>Description: </strong><%= @project.description %></p>
  <p><strong>Complete By: </strong><%= @project.due_date %></p>
  <p><strong>Created By: </strong><%= @project.user.first_name %></p>
  <p><strong>Members: </strong>
  <p><%= User.find( @project.memberships.map(&:user_id) ).map(&:first_name).join(', ') %></p>
  <p><strong>Tags:</strong></p>
    <p><%= @project.tags.map(&:title).join(", ") %></p>
  <%= link_to "View Discussions", project_discussions_path(@project, @discussion), class: "btn btn-primary btn-lg" %><br><br>
  <%= link_to "Edit Project?", edit_project_path, class: "btn btn-primary btn-xs" %>
  <%= link_to "Scrap Project?!", project_path(@project),
  method: :delete,
  data: {confirm: "Are you sure you wish to scrap your project?! This is your last chance man.."}, class: "btn btn-danger btn-xs"  %>
  <% if @project.user_id != current_user.id %> 
    <% if @favourite %>
      <%= link_to "Favourited", project_favourite_path(@project, @favourite), method: :delete, class: "btn btn-success btn-xs" %>
    <% else %>
      <%= link_to "Add To Favourites", project_favourites_path(@project), method: :post, class: "btn btn-info btn-xs" %>
    <% end %>
  <% else %>
    <p>You created this project! You cannot favourite it.</p>
  <% end %>  
</div>

<hr>

<div class="container" id="task-container">
  <%= render partial: 'tasks/task_project' %>
</div>

<div class="container">
  <h2>Start a New Discussion for: <%= @project.title %></h2>
  <%= form_for [@project, @discussion] do |f| %>
    <%= f.label :title %>
    <%= f.text_area :title, class:"form-control" %><br>
    <%= f.label :description %>
    <%= f.text_field :description, class:"form-control"%><br>
    <%= f.submit class: "btn btn-info btn-md" %>
    <%= link_to "View Discussions", project_discussions_path(@project, @discussion), class: "btn btn-primary btn-md" %>
  <br>
  <br>
  <% end %>
</div>